name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: '6.1'
    
    - name: Run tests
      run: |
        swift test --enable-code-coverage

        PROFDATA="$(swift test --show-codecov-path)"
        echo "profdata: $PROFDATA"
  
        BIN_PATH="$(swift build --configuration debug --show-bin-path)"
        echo "bin path: $BIN_PATH"
  
        llvm-cov report \
          "$BIN_PATH"/* \
          -instr-profile "$PROFDATA" \
          -ignore-filename-regex='(.build|/Tests/)' \
          | tee coverage-report.txt
  
        TOTAL=$(grep -E '^TOTAL' coverage-report.txt | awk '{print $NF}')
        {
          echo "## SwiftPM Coverage"
          echo ""
          echo "Total line coverage: $TOTAL"
          echo ""
          echo '```'
          cat coverage-report.txt
          echo '```'
        } >> "$GITHUB_STEP_SUMMARY"
